version: '3.1'

services:
  db:
    image: postgres
    restart: always
    volumes:
     - /home/ignat/blogData/db:/var/lib/postgresql/data
    environment:
        POSTGRES_PASSWORD: root
        POSTGRES_DB: blog

  blog:
    image: nakhay/blog
    restart: always
    volumes:
      - /home/ignat/blogData/uploads:/home/ignat/blogData/uploads
	  - /home/ignat/dev/blog-deploy/application.properties:/opt/application.properties
    ports:
      - 8080:8080
    depends_on: 
      - db
